In [1]:
import pandas
attr = pandas.read_csv('LazegaLawyers/ELattr.dat', sep=' ', header=None)

In [8]:
ground_truth = attr[1].to_numpy()

In [2]:
import pandas as pd
gender = pd.get_dummies(attr[2], prefix='gender')
office = pd.get_dummies(attr[3], prefix='office')
practice = pd.get_dummies(attr[6], prefix='practice')
law_school = pd.get_dummies(attr[7], prefix='law_school')

In [3]:
encoded = gender.join(office).join(practice).join(law_school).join(attr[4]).join(attr[5])

In [4]:
import numpy as np
np_data = encoded.to_numpy()


In [5]:
import sklearn
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(np_data)
np_data_normalized = scaler.transform(np_data)


In [16]:
from spectral_clustering import SpectralClustering
sc = SpectralClustering(2, gamma=0.1)
sc.fit(np_data_normalized)

In [17]:
sc.embedding_features

array([[-0.11867817,  0.02301212],
       [-0.11867817, -0.00365817],
       [-0.11867817,  0.02401904],
       [-0.11867817,  0.01433933],
       [-0.11867817,  0.04248425],
       [-0.11867817,  0.02825224],
       [-0.11867817,  0.01742075],
       [-0.11867817,  0.03046651],
       [-0.11867817, -0.00299648],
       [-0.11867817,  0.01279376],
       [-0.11867817,  0.01941364],
       [-0.11867817,  0.01144439],
       [-0.11867817,  0.02793069],
       [-0.11867817, -0.01401642],
       [-0.11867817, -0.00875551],
       [-0.11867817, -0.00268936],
       [-0.11867817, -0.00283753],
       [-0.11867817,  0.03337213],
       [-0.11867817, -0.0027667 ],
       [-0.11867817,  0.01864928],
       [-0.11867817,  0.02657204],
       [-0.11867817,  0.02689877],
       [-0.11867817,  0.02638376],
       [-0.11867817,  0.02628558],
       [-0.11867817,  0.01160049],
       [-0.11867817,  0.02743444],
       [-0.11867817, -0.00499631],
       [-0.11867817,  0.01160151],
       [-0.11867817,

In [11]:
print(np.sum(ground_truth==1))

36


In [19]:
np.where(sc.labels_==1)

(array([43], dtype=int64),)

In [21]:
np_data_normalized[42:45,:]

array([[0.        , 1.        , 1.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.12903226, 0.51219512],
       [0.        , 1.        , 0.        , 0.        , 1.        ,
        0.        , 1.        , 1.        , 0.        , 0.        ,
        0.12903226, 0.65853659],
       [1.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 1.        ,
        0.06451613, 0.29268293]])

In [ ]:
from sklearn.metrics.cluster import normalized_mutual_info_score
nmi = normalized_mutual_info_score(ground_truth, cat_1)